// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkgo

// Generated from OpenAPI doc version 1.0.0 and generator version 2.795.8

import (
	"context"
	"fmt"
	"github.com/img-src-io/sdk-go/internal/config"
	"github.com/img-src-io/sdk-go/internal/hooks"
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
	"github.com/img-src-io/sdk-go/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Production
	"https://api.img-src.io",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// Imgsrc - img-src API: Image processing and delivery API.
//
// A serverless image processing and delivery API built on Cloudflare Workers with parameter-driven image transformation and on-demand transcoding.
//
// ## Features
//
// - **Image Upload**: Store original images in R2 with SHA256-based deduplication
// - **On-Demand Transformation**: Resize, crop, and convert images via URL parameters
// - **Format Conversion**: WebP, AVIF, JPEG, PNG output formats
// - **Path Organization**: Organize images into folders with multiple paths per image
// - **CDN Caching**: Automatic edge caching for transformed images
//
// ## Authentication
//
// Authenticate using API Keys with `imgsrc_` prefix. Create your API key at https://img-src.io/settings
//
// ## Rate Limiting
//
// - **Free Plan**: 100 requests/minute
// - **Pro Plan**: 500 requests/minute
//
// Rate limit headers are included in all responses.
type Imgsrc struct {
	SDKVersion string
	Settings   *Settings
	Presets    *Presets
	Usage      *Usage
	Images     *Images

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Imgsrc)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Imgsrc) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Imgsrc) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *Imgsrc) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Imgsrc) {
		sdk.sdkConfiguration.Client = client
	}
}

// WithSecurity configures the SDK to use the provided security details
func WithSecurity(bearerAuth string) SDKOption {
	return func(sdk *Imgsrc) {
		security := components.Security{BearerAuth: bearerAuth}
		sdk.sdkConfiguration.Security = utils.AsSecuritySource(&security)
	}
}

// WithSecuritySource configures the SDK to invoke the Security Source function on each method call to determine authentication
func WithSecuritySource(security func(context.Context) (components.Security, error)) SDKOption {
	return func(sdk *Imgsrc) {
		sdk.sdkConfiguration.Security = func(ctx context.Context) (interface{}, error) {
			return security(ctx)
		}
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Imgsrc) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Imgsrc) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *Imgsrc {
	sdk := &Imgsrc{
		SDKVersion: "0.2.1",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.2.1 2.795.8 1.0.0 github.com/img-src-io/sdk-go",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Settings = newSettings(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Presets = newPresets(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Usage = newUsage(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Images = newImages(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
