// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type CreateSignedURLRequest struct {
	ID   string                             `pathParam:"style=simple,explode=false,name=id"`
	Body *components.CreateSignedURLRequest `request:"mediaType=application/json"`
}

func (c CreateSignedURLRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSignedURLRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSignedURLRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateSignedURLRequest) GetBody() *components.CreateSignedURLRequest {
	if c == nil {
		return nil
	}
	return c.Body
}

type CreateSignedURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Signed URL created
	SignedURLResponse *components.SignedURLResponse
}

func (c CreateSignedURLResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSignedURLResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSignedURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSignedURLResponse) GetSignedURLResponse() *components.SignedURLResponse {
	if c == nil {
		return nil
	}
	return c.SignedURLResponse
}
