// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type DeleteImagePathRequest struct {
	Username string `pathParam:"style=simple,explode=false,name=username"`
	Filepath string `pathParam:"style=simple,explode=false,name=filepath"`
}

func (d *DeleteImagePathRequest) GetUsername() string {
	if d == nil {
		return ""
	}
	return d.Username
}

func (d *DeleteImagePathRequest) GetFilepath() string {
	if d == nil {
		return ""
	}
	return d.Filepath
}

type DeleteImagePathResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Path deleted
	PathDeleteResponse *components.PathDeleteResponse
}

func (d DeleteImagePathResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteImagePathResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteImagePathResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteImagePathResponse) GetPathDeleteResponse() *components.PathDeleteResponse {
	if d == nil {
		return nil
	}
	return d.PathDeleteResponse
}
