// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type DeleteImageRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteImageRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Image deleted
	DeleteResponse *components.DeleteResponse
}

func (d DeleteImageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteImageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteImageResponse) GetDeleteResponse() *components.DeleteResponse {
	if d == nil {
		return nil
	}
	return d.DeleteResponse
}
