// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type DeletePresetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeletePresetRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeletePresetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Preset deleted
	DeletePresetResponse *components.DeletePresetResponse
}

func (d DeletePresetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeletePresetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeletePresetResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeletePresetResponse) GetDeletePresetResponse() *components.DeletePresetResponse {
	if d == nil {
		return nil
	}
	return d.DeletePresetResponse
}
