// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type GetImageRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetImageRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Image metadata
	MetadataResponse *components.MetadataResponse
}

func (g GetImageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetImageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetImageResponse) GetMetadataResponse() *components.MetadataResponse {
	if g == nil {
		return nil
	}
	return g.MetadataResponse
}
