// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type GetPresetRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPresetRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetPresetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Preset details
	Preset *components.Preset
}

func (g GetPresetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPresetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPresetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPresetResponse) GetPreset() *components.Preset {
	if g == nil {
		return nil
	}
	return g.Preset
}
