// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type GetSettingsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User settings
	SettingsResponse *components.SettingsResponse
}

func (g GetSettingsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSettingsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSettingsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSettingsResponse) GetSettingsResponse() *components.SettingsResponse {
	if g == nil {
		return nil
	}
	return g.SettingsResponse
}
