// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type GetUsageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Usage statistics
	UsageResponse *components.UsageResponse
}

func (g GetUsageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsageResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUsageResponse) GetUsageResponse() *components.UsageResponse {
	if g == nil {
		return nil
	}
	return g.UsageResponse
}
