// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type ListPresetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of presets
	ListPresetsResponse *components.ListPresetsResponse
}

func (l ListPresetsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPresetsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPresetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListPresetsResponse) GetListPresetsResponse() *components.ListPresetsResponse {
	if l == nil {
		return nil
	}
	return l.ListPresetsResponse
}
