// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
	"github.com/img-src-io/sdk-go/optionalnullable"
)

type ListImagesRequest struct {
	Limit  *int64                                   `default:"50" queryParam:"style=form,explode=true,name=limit"`
	Offset optionalnullable.OptionalNullable[int64] `default:"0" queryParam:"style=form,explode=true,name=offset"`
	Path   *string                                  `queryParam:"style=form,explode=true,name=path"`
}

func (l ListImagesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListImagesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListImagesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListImagesRequest) GetOffset() optionalnullable.OptionalNullable[int64] {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListImagesRequest) GetPath() *string {
	if l == nil {
		return nil
	}
	return l.Path
}

type ListImagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of images
	ImageListResponse *components.ImageListResponse

	Next func() (*ListImagesResponse, error)
}

func (l ListImagesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListImagesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListImagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListImagesResponse) GetImageListResponse() *components.ImageListResponse {
	if l == nil {
		return nil
	}
	return l.ImageListResponse
}
