// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type SearchImagesRequest struct {
	Q     string `queryParam:"style=form,explode=true,name=q"`
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
}

func (s SearchImagesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchImagesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchImagesRequest) GetQ() string {
	if s == nil {
		return ""
	}
	return s.Q
}

func (s *SearchImagesRequest) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

type SearchImagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Search results
	SearchResponse *components.SearchResponse
}

func (s SearchImagesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchImagesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchImagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SearchImagesResponse) GetSearchResponse() *components.SearchResponse {
	if s == nil {
		return nil
	}
	return s.SearchResponse
}
