// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type UpdateSettingsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Updated user settings
	SettingsUpdateResponse *components.SettingsUpdateResponse
}

func (u UpdateSettingsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSettingsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSettingsResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSettingsResponse) GetSettingsUpdateResponse() *components.SettingsUpdateResponse {
	if u == nil {
		return nil
	}
	return u.SettingsUpdateResponse
}
