// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type UpdateVisibilityRequest struct {
	ID   string                                `pathParam:"style=simple,explode=false,name=id"`
	Body components.UpdateVisibilityRequest    `request:"mediaType=application/json"`
}

func (u UpdateVisibilityRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateVisibilityRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateVisibilityRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateVisibilityRequest) GetBody() components.UpdateVisibilityRequest {
	if u == nil {
		return components.UpdateVisibilityRequest{}
	}
	return u.Body
}

type UpdateVisibilityResponse struct {
	HTTPMeta                 components.HTTPMetadata `json:"-"`
	// Visibility updated successfully
	UpdateVisibilityResponse *components.UpdateVisibilityResponse
}

func (u UpdateVisibilityResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateVisibilityResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateVisibilityResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateVisibilityResponse) GetUpdateVisibilityResponse() *components.UpdateVisibilityResponse {
	if u == nil {
		return nil
	}
	return u.UpdateVisibilityResponse
}
