// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type UpdatePresetRequest struct {
	ID   string                          `pathParam:"style=simple,explode=false,name=id"`
	Body *components.UpdatePresetRequest `request:"mediaType=application/json"`
}

func (u UpdatePresetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePresetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePresetRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdatePresetRequest) GetBody() *components.UpdatePresetRequest {
	if u == nil {
		return nil
	}
	return u.Body
}

type UpdatePresetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Preset updated
	Preset *components.Preset
}

func (u UpdatePresetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePresetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePresetResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdatePresetResponse) GetPreset() *components.Preset {
	if u == nil {
		return nil
	}
	return u.Preset
}
