// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/models/components"
)

type File struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (f *File) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

func (f *File) GetContent() any {
	if f == nil {
		return nil
	}
	return f.Content
}

type UploadImageRequestBody struct {
	// Image file to upload
	File *File `multipartForm:"file,name=file"`
	// Target path for organizing the image
	TargetPath *string `multipartForm:"name=target_path"`
}

func (u UploadImageRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadImageRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadImageRequestBody) GetFile() *File {
	if u == nil {
		return nil
	}
	return u.File
}

func (u *UploadImageRequestBody) GetTargetPath() *string {
	if u == nil {
		return nil
	}
	return u.TargetPath
}

type UploadImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Image uploaded successfully
	UploadResponse *components.UploadResponse
}

func (u UploadImageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadImageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UploadImageResponse) GetUploadResponse() *components.UploadResponse {
	if u == nil {
		return nil
	}
	return u.UploadResponse
}
