// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ActiveSignedUrl struct {
	// The signed URL
	SignedURL string `json:"signed_url"`
	// Unix timestamp when the signed URL expires
	ExpiresAt int64 `json:"expires_at"`
}

func (a *ActiveSignedUrl) GetSignedURL() string {
	if a == nil {
		return ""
	}
	return a.SignedURL
}

func (a *ActiveSignedUrl) GetExpiresAt() int64 {
	if a == nil {
		return 0
	}
	return a.ExpiresAt
}
