// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AvailableFormats struct {
	// WebP format URL
	Webp string `json:"webp"`
	// AVIF format URL
	Avif string `json:"avif"`
	// JPEG format URL
	Jpeg string `json:"jpeg"`
}

func (a *AvailableFormats) GetWebp() string {
	if a == nil {
		return ""
	}
	return a.Webp
}

func (a *AvailableFormats) GetAvif() string {
	if a == nil {
		return ""
	}
	return a.Avif
}

func (a *AvailableFormats) GetJpeg() string {
	if a == nil {
		return ""
	}
	return a.Jpeg
}
