// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CdnUrls struct {
	// Original format URL
	Original string `json:"original"`
	// WebP format URL
	Webp string `json:"webp"`
	// AVIF format URL
	Avif string `json:"avif"`
	// JPEG format URL
	Jpeg string `json:"jpeg"`
	// PNG format URL
	Png string `json:"png"`
}

func (c *CdnUrls) GetOriginal() string {
	if c == nil {
		return ""
	}
	return c.Original
}

func (c *CdnUrls) GetWebp() string {
	if c == nil {
		return ""
	}
	return c.Webp
}

func (c *CdnUrls) GetAvif() string {
	if c == nil {
		return ""
	}
	return c.Avif
}

func (c *CdnUrls) GetJpeg() string {
	if c == nil {
		return ""
	}
	return c.Jpeg
}

func (c *CdnUrls) GetPng() string {
	if c == nil {
		return ""
	}
	return c.Png
}
