// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreatePresetRequest struct {
	// Preset name (1-50 characters)
	Name string `json:"name"`
	// Optional description (max 200 characters)
	Description *string `json:"description,omitzero"`
	// Transformation parameters
	Params map[string]any `json:"params"`
}

func (c *CreatePresetRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatePresetRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreatePresetRequest) GetParams() map[string]any {
	if c == nil {
		return map[string]any{}
	}
	return c.Params
}
