// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/img-src-io/sdk-go/internal/utils"
)

type Fit string

const (
	FitCover     Fit = "cover"
	FitContain   Fit = "contain"
	FitFill      Fit = "fill"
	FitScaleDown Fit = "scale-down"
)

func (e Fit) ToPointer() *Fit {
	return &e
}
func (e *Fit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cover":
		fallthrough
	case "contain":
		fallthrough
	case "fill":
		fallthrough
	case "scale-down":
		*e = Fit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Fit: %v", v)
	}
}

type Format string

const (
	FormatWebp Format = "webp"
	FormatAvif Format = "avif"
	FormatJpeg Format = "jpeg"
	FormatPng  Format = "png"
)

func (e Format) ToPointer() *Format {
	return &e
}
func (e *Format) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "webp":
		fallthrough
	case "avif":
		fallthrough
	case "jpeg":
		fallthrough
	case "png":
		*e = Format(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Format: %v", v)
	}
}

// Transformation - Optional image transformation parameters
type Transformation struct {
	Width   *int64  `json:"width,omitzero"`
	Height  *int64  `json:"height,omitzero"`
	Fit     *Fit    `json:"fit,omitzero"`
	Quality *int64  `json:"quality,omitzero"`
	Format  *Format `json:"format,omitzero"`
}

func (t *Transformation) GetWidth() *int64 {
	if t == nil {
		return nil
	}
	return t.Width
}

func (t *Transformation) GetHeight() *int64 {
	if t == nil {
		return nil
	}
	return t.Height
}

func (t *Transformation) GetFit() *Fit {
	if t == nil {
		return nil
	}
	return t.Fit
}

func (t *Transformation) GetQuality() *int64 {
	if t == nil {
		return nil
	}
	return t.Quality
}

func (t *Transformation) GetFormat() *Format {
	if t == nil {
		return nil
	}
	return t.Format
}

type CreateSignedURLRequest struct {
	// Expiration time in seconds (60-86400, default 3600)
	ExpiresInSeconds *int64 `default:"3600" json:"expires_in_seconds"`
	// Optional image transformation parameters
	Transformation *Transformation `json:"transformation,omitzero"`
}

func (c CreateSignedURLRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSignedURLRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSignedURLRequest) GetExpiresInSeconds() *int64 {
	if c == nil {
		return nil
	}
	return c.ExpiresInSeconds
}

func (c *CreateSignedURLRequest) GetTransformation() *Transformation {
	if c == nil {
		return nil
	}
	return c.Transformation
}
