// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Credits struct {
	// Storage usage in bytes
	StorageBytes int64 `json:"storage_bytes"`
	// API requests used in current period
	APIRequests int64 `json:"api_requests"`
	// Transformations used in current period
	Transformations int64 `json:"transformations"`
}

func (c *Credits) GetStorageBytes() int64 {
	if c == nil {
		return 0
	}
	return c.StorageBytes
}

func (c *Credits) GetAPIRequests() int64 {
	if c == nil {
		return 0
	}
	return c.APIRequests
}

func (c *Credits) GetTransformations() int64 {
	if c == nil {
		return 0
	}
	return c.Transformations
}
