// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CurrentPeriod struct {
	// Period identifier (YYYY-MM format)
	Period string `json:"period"`
	// Unix timestamp of period start
	PeriodStart int64 `json:"period_start"`
	// Unix timestamp of period end
	PeriodEnd int64 `json:"period_end"`
	// Uploads this period
	Uploads int64 `json:"uploads"`
	// Bandwidth used this period in bytes
	BandwidthBytes int64 `json:"bandwidth_bytes"`
	// API requests this period
	APIRequests int64 `json:"api_requests"`
	// Image transformations this period
	Transformations int64 `json:"transformations"`
}

func (c *CurrentPeriod) GetPeriod() string {
	if c == nil {
		return ""
	}
	return c.Period
}

func (c *CurrentPeriod) GetPeriodStart() int64 {
	if c == nil {
		return 0
	}
	return c.PeriodStart
}

func (c *CurrentPeriod) GetPeriodEnd() int64 {
	if c == nil {
		return 0
	}
	return c.PeriodEnd
}

func (c *CurrentPeriod) GetUploads() int64 {
	if c == nil {
		return 0
	}
	return c.Uploads
}

func (c *CurrentPeriod) GetBandwidthBytes() int64 {
	if c == nil {
		return 0
	}
	return c.BandwidthBytes
}

func (c *CurrentPeriod) GetAPIRequests() int64 {
	if c == nil {
		return 0
	}
	return c.APIRequests
}

func (c *CurrentPeriod) GetTransformations() int64 {
	if c == nil {
		return 0
	}
	return c.Transformations
}
