// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"time"
)

type DeleteResponse struct {
	// Operation success flag
	Success bool `json:"success"`
	// Human-readable message
	Message string `json:"message"`
	// List of deleted paths
	DeletedPaths []string `json:"deleted_paths,omitzero"`
	// Deletion timestamp
	DeletedAt time.Time `json:"deleted_at"`
}

func (d DeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteResponse) GetDeletedPaths() []string {
	if d == nil {
		return nil
	}
	return d.DeletedPaths
}

func (d *DeleteResponse) GetDeletedAt() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.DeletedAt
}
