// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeletePresetResponse struct {
	// Operation success flag
	Success bool `json:"success"`
	// Human-readable message
	Message string `json:"message"`
}

func (d *DeletePresetResponse) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeletePresetResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}
