// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ErrorDetail struct {
	// Error code (e.g., NOT_FOUND, UNAUTHORIZED, VALIDATION_ERROR)
	Code string `json:"code"`
	// Human-readable error message
	Message string `json:"message"`
	// HTTP status code
	Status int64 `json:"status"`
	// Request path (optional)
	Path *string `json:"path,omitzero"`
}

func (e *ErrorDetail) GetCode() string {
	if e == nil {
		return ""
	}
	return e.Code
}

func (e *ErrorDetail) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *ErrorDetail) GetStatus() int64 {
	if e == nil {
		return 0
	}
	return e.Status
}

func (e *ErrorDetail) GetPath() *string {
	if e == nil {
		return nil
	}
	return e.Path
}
