// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FolderItem struct {
	// Folder name
	Name string `json:"name"`
	// Number of images in folder (including subfolders)
	ImageCount int64 `json:"image_count"`
}

func (f *FolderItem) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FolderItem) GetImageCount() int64 {
	if f == nil {
		return 0
	}
	return f.ImageCount
}
