// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type HateoasLinks struct {
	// Link to the resource itself
	Self string `json:"self"`
	// Link to delete the resource
	Delete string `json:"delete"`
}

func (h *HateoasLinks) GetSelf() string {
	if h == nil {
		return ""
	}
	return h.Self
}

func (h *HateoasLinks) GetDelete() string {
	if h == nil {
		return ""
	}
	return h.Delete
}
