// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ImageListResponse struct {
	Images  []ImageListItem `json:"images"`
	Folders []FolderItem    `json:"folders"`
	// Total count of images (in current path)
	Total int64 `json:"total"`
	// Maximum items per page
	Limit int64 `json:"limit"`
	// Current offset
	Offset int64 `json:"offset"`
	// Whether more items exist
	HasMore bool `json:"has_more"`
	// Current path filter (if any)
	PathFilter *string `json:"path_filter,omitzero"`
}

func (i *ImageListResponse) GetImages() []ImageListItem {
	if i == nil {
		return []ImageListItem{}
	}
	return i.Images
}

func (i *ImageListResponse) GetFolders() []FolderItem {
	if i == nil {
		return []FolderItem{}
	}
	return i.Folders
}

func (i *ImageListResponse) GetTotal() int64 {
	if i == nil {
		return 0
	}
	return i.Total
}

func (i *ImageListResponse) GetLimit() int64 {
	if i == nil {
		return 0
	}
	return i.Limit
}

func (i *ImageListResponse) GetOffset() int64 {
	if i == nil {
		return 0
	}
	return i.Offset
}

func (i *ImageListResponse) GetHasMore() bool {
	if i == nil {
		return false
	}
	return i.HasMore
}

func (i *ImageListResponse) GetPathFilter() *string {
	if i == nil {
		return nil
	}
	return i.PathFilter
}
