// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"time"
)

type ImageMetadata struct {
	// Full SHA256 hash
	Hash string `json:"hash"`
	// Original filename as uploaded
	OriginalFilename string `json:"original_filename"`
	// File size in bytes
	Size int64 `json:"size"`
	// Upload timestamp
	UploadedAt time.Time `json:"uploaded_at"`
	// MIME type
	MimeType string `json:"mime_type"`
	// Image width in pixels
	Width *int64 `json:"width,omitzero"`
	// Image height in pixels
	Height *int64 `json:"height,omitzero"`
	// Dominant color as 6-digit hex (without #)
	DominantColor *string `json:"dominant_color,omitzero"`
}

func (i ImageMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageMetadata) GetHash() string {
	if i == nil {
		return ""
	}
	return i.Hash
}

func (i *ImageMetadata) GetOriginalFilename() string {
	if i == nil {
		return ""
	}
	return i.OriginalFilename
}

func (i *ImageMetadata) GetSize() int64 {
	if i == nil {
		return 0
	}
	return i.Size
}

func (i *ImageMetadata) GetUploadedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UploadedAt
}

func (i *ImageMetadata) GetMimeType() string {
	if i == nil {
		return ""
	}
	return i.MimeType
}

func (i *ImageMetadata) GetWidth() *int64 {
	if i == nil {
		return nil
	}
	return i.Width
}

func (i *ImageMetadata) GetHeight() *int64 {
	if i == nil {
		return nil
	}
	return i.Height
}

func (i *ImageMetadata) GetDominantColor() *string {
	if i == nil {
		return nil
	}
	return i.DominantColor
}
