// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ImageDimensions struct {
	// Image width in pixels
	Width int64 `json:"width"`
	// Image height in pixels
	Height int64 `json:"height"`
}

func (i *ImageDimensions) GetWidth() int64 {
	if i == nil {
		return 0
	}
	return i.Width
}

func (i *ImageDimensions) GetHeight() int64 {
	if i == nil {
		return 0
	}
	return i.Height
}
