// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"time"
)

type ImageListItem struct {
	// Image ID
	ID string `json:"id"`
	// Original filename as uploaded
	OriginalFilename string `json:"original_filename"`
	// Sanitized filename (URL-safe)
	SanitizedFilename *string `json:"sanitized_filename,omitzero"`
	// File size in bytes
	Size int64 `json:"size"`
	// Upload timestamp
	UploadedAt time.Time `json:"uploaded_at"`
	// API endpoint URL
	URL string `json:"url"`
	// CDN URL for direct access
	CdnURL *string `json:"cdn_url,omitzero"`
	// All paths for this image
	Paths           []string         `json:"paths"`
	Visibility      Visibility       `json:"visibility"`
	ActiveSignedUrl *ActiveSignedUrl `json:"active_signed_url,omitzero"`
}

func (i ImageListItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageListItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageListItem) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *ImageListItem) GetOriginalFilename() string {
	if i == nil {
		return ""
	}
	return i.OriginalFilename
}

func (i *ImageListItem) GetSanitizedFilename() *string {
	if i == nil {
		return nil
	}
	return i.SanitizedFilename
}

func (i *ImageListItem) GetSize() int64 {
	if i == nil {
		return 0
	}
	return i.Size
}

func (i *ImageListItem) GetUploadedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UploadedAt
}

func (i *ImageListItem) GetURL() string {
	if i == nil {
		return ""
	}
	return i.URL
}

func (i *ImageListItem) GetCdnURL() *string {
	if i == nil {
		return nil
	}
	return i.CdnURL
}

func (i *ImageListItem) GetPaths() []string {
	if i == nil {
		return []string{}
	}
	return i.Paths
}

func (i *ImageListItem) GetVisibility() Visibility {
	if i == nil {
		return Visibility("")
	}
	return i.Visibility
}

func (i *ImageListItem) GetActiveSignedUrl() *ActiveSignedUrl {
	if i == nil {
		return nil
	}
	return i.ActiveSignedUrl
}
