// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListPresetsResponse struct {
	Presets []Preset `json:"presets"`
	// Total number of presets
	Total int64 `json:"total"`
}

func (l *ListPresetsResponse) GetPresets() []Preset {
	if l == nil {
		return []Preset{}
	}
	return l.Presets
}

func (l *ListPresetsResponse) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}
