// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MetadataResponse struct {
	// Image ID
	ID         string        `json:"id"`
	Metadata   ImageMetadata `json:"metadata"`
	Urls       CdnUrls       `json:"urls"`
	Visibility Visibility    `json:"visibility"`
	Links      HateoasLinks  `json:"_links"`
}

func (m *MetadataResponse) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MetadataResponse) GetMetadata() ImageMetadata {
	if m == nil {
		return ImageMetadata{}
	}
	return m.Metadata
}

func (m *MetadataResponse) GetUrls() CdnUrls {
	if m == nil {
		return CdnUrls{}
	}
	return m.Urls
}

func (m *MetadataResponse) GetVisibility() Visibility {
	if m == nil {
		return Visibility("")
	}
	return m.Visibility
}

func (m *MetadataResponse) GetLinks() HateoasLinks {
	if m == nil {
		return HateoasLinks{}
	}
	return m.Links
}
