// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"time"
)

type PathDeleteResponse struct {
	// Operation success flag
	Success bool `json:"success"`
	// Human-readable message
	Message string `json:"message"`
	// Remaining paths for the image
	RemainingPaths []string `json:"remaining_paths"`
	// Whether the image itself was deleted (last path removed)
	ImageDeleted bool `json:"image_deleted"`
	// Deletion timestamp
	DeletedAt time.Time `json:"deleted_at"`
}

func (p PathDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PathDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PathDeleteResponse) GetSuccess() bool {
	if p == nil {
		return false
	}
	return p.Success
}

func (p *PathDeleteResponse) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PathDeleteResponse) GetRemainingPaths() []string {
	if p == nil {
		return []string{}
	}
	return p.RemainingPaths
}

func (p *PathDeleteResponse) GetImageDeleted() bool {
	if p == nil {
		return false
	}
	return p.ImageDeleted
}

func (p *PathDeleteResponse) GetDeletedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.DeletedAt
}
