// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlanLimits struct {
	// Maximum uploads per month (null = unlimited)
	MaxUploadsPerMonth *int64 `json:"max_uploads_per_month"`
	// Maximum storage in bytes (null = unlimited)
	MaxStorageBytes *int64 `json:"max_storage_bytes"`
	// Maximum bandwidth per month in bytes (null = unlimited)
	MaxBandwidthPerMonth *int64 `json:"max_bandwidth_per_month"`
	// Maximum API requests per month (null = unlimited)
	MaxAPIRequestsPerMonth *int64 `json:"max_api_requests_per_month"`
	// Maximum image transformations per month (null = unlimited)
	MaxTransformationsPerMonth *int64 `json:"max_transformations_per_month"`
}

func (p *PlanLimits) GetMaxUploadsPerMonth() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxUploadsPerMonth
}

func (p *PlanLimits) GetMaxStorageBytes() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxStorageBytes
}

func (p *PlanLimits) GetMaxBandwidthPerMonth() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxBandwidthPerMonth
}

func (p *PlanLimits) GetMaxAPIRequestsPerMonth() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxAPIRequestsPerMonth
}

func (p *PlanLimits) GetMaxTransformationsPerMonth() *int64 {
	if p == nil {
		return nil
	}
	return p.MaxTransformationsPerMonth
}
