// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Preset struct {
	// Preset ID
	ID string `json:"id"`
	// Preset name
	Name string `json:"name"`
	// Optional description
	Description *string `json:"description"`
	// Transformation parameters
	Params map[string]any `json:"params"`
	// Creation timestamp (Unix epoch)
	CreatedAt int64 `json:"created_at"`
	// Last update timestamp (Unix epoch)
	UpdatedAt int64 `json:"updated_at"`
	// Number of times this preset has been used
	UsageCount int64 `json:"usage_count"`
}

func (p *Preset) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Preset) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Preset) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Preset) GetParams() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.Params
}

func (p *Preset) GetCreatedAt() int64 {
	if p == nil {
		return 0
	}
	return p.CreatedAt
}

func (p *Preset) GetUpdatedAt() int64 {
	if p == nil {
		return 0
	}
	return p.UpdatedAt
}

func (p *Preset) GetUsageCount() int64 {
	if p == nil {
		return 0
	}
	return p.UsageCount
}
