// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SearchResponse struct {
	Results []SearchResult `json:"results"`
	// Total number of matches
	Total int64 `json:"total"`
	// Original search query
	Query string `json:"query"`
}

func (s *SearchResponse) GetResults() []SearchResult {
	if s == nil {
		return []SearchResult{}
	}
	return s.Results
}

func (s *SearchResponse) GetTotal() int64 {
	if s == nil {
		return 0
	}
	return s.Total
}

func (s *SearchResponse) GetQuery() string {
	if s == nil {
		return ""
	}
	return s.Query
}
