// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"time"
)

type SearchResult struct {
	// Image ID
	ID string `json:"id"`
	// Original filename
	OriginalFilename string `json:"original_filename"`
	// Sanitized filename
	SanitizedFilename *string `json:"sanitized_filename,omitzero"`
	// All paths for this image
	Paths []string `json:"paths"`
	// File size in bytes
	Size int64 `json:"size"`
	// Upload timestamp
	UploadedAt time.Time `json:"uploaded_at"`
	// API endpoint URL
	URL string `json:"url"`
	// CDN URL
	CdnURL     *string    `json:"cdn_url,omitzero"`
	Visibility Visibility `json:"visibility"`
}

func (s SearchResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchResult) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SearchResult) GetOriginalFilename() string {
	if s == nil {
		return ""
	}
	return s.OriginalFilename
}

func (s *SearchResult) GetSanitizedFilename() *string {
	if s == nil {
		return nil
	}
	return s.SanitizedFilename
}

func (s *SearchResult) GetPaths() []string {
	if s == nil {
		return []string{}
	}
	return s.Paths
}

func (s *SearchResult) GetSize() int64 {
	if s == nil {
		return 0
	}
	return s.Size
}

func (s *SearchResult) GetUploadedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UploadedAt
}

func (s *SearchResult) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *SearchResult) GetCdnURL() *string {
	if s == nil {
		return nil
	}
	return s.CdnURL
}

func (s *SearchResult) GetVisibility() Visibility {
	if s == nil {
		return Visibility("")
	}
	return s.Visibility
}
