// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SettingsResponse struct {
	Settings UserSettings `json:"settings"`
}

func (s *SettingsResponse) GetSettings() UserSettings {
	if s == nil {
		return UserSettings{}
	}
	return s.Settings
}
