// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SettingsUpdateResponse struct {
	Settings UserSettings `json:"settings"`
	// Human-readable message
	Message string `json:"message"`
}

func (s *SettingsUpdateResponse) GetSettings() UserSettings {
	if s == nil {
		return UserSettings{}
	}
	return s.Settings
}

func (s *SettingsUpdateResponse) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}
