// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignedURLResponse struct {
	// Time-limited signed URL
	SignedURL string `json:"signed_url"`
	// Expiration timestamp (Unix epoch)
	ExpiresAt int64 `json:"expires_at"`
	// Seconds until expiration
	ExpiresInSeconds int64 `json:"expires_in_seconds"`
}

func (s *SignedURLResponse) GetSignedURL() string {
	if s == nil {
		return ""
	}
	return s.SignedURL
}

func (s *SignedURLResponse) GetExpiresAt() int64 {
	if s == nil {
		return 0
	}
	return s.ExpiresAt
}

func (s *SignedURLResponse) GetExpiresInSeconds() int64 {
	if s == nil {
		return 0
	}
	return s.ExpiresInSeconds
}
