// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateVisibilityRequest struct {
	// Target visibility
	Visibility Visibility `json:"visibility"`
}

func (u *UpdateVisibilityRequest) GetVisibility() Visibility {
	if u == nil {
		return Visibility("")
	}
	return u.Visibility
}
