// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/optionalnullable"
)

type UpdateSettingsRequest struct {
	// Preferred delivery formats (ordered)
	DeliveryFormats []string `json:"delivery_formats,omitzero"`
	// Default image quality (1-100)
	DefaultQuality *int64 `json:"default_quality,omitzero"`
	// Default fit mode
	DefaultFitMode *string `json:"default_fit_mode,omitzero"`
	// Default maximum width (null to clear)
	DefaultMaxWidth optionalnullable.OptionalNullable[int64] `json:"default_max_width,omitzero"`
	// Default maximum height (null to clear)
	DefaultMaxHeight optionalnullable.OptionalNullable[int64] `json:"default_max_height,omitzero"`
	// UI theme
	Theme *string `json:"theme,omitzero"`
	// UI language
	Language *string `json:"language,omitzero"`
}

func (u UpdateSettingsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSettingsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSettingsRequest) GetDeliveryFormats() []string {
	if u == nil {
		return nil
	}
	return u.DeliveryFormats
}

func (u *UpdateSettingsRequest) GetDefaultQuality() *int64 {
	if u == nil {
		return nil
	}
	return u.DefaultQuality
}

func (u *UpdateSettingsRequest) GetDefaultFitMode() *string {
	if u == nil {
		return nil
	}
	return u.DefaultFitMode
}

func (u *UpdateSettingsRequest) GetDefaultMaxWidth() optionalnullable.OptionalNullable[int64] {
	if u == nil {
		return nil
	}
	return u.DefaultMaxWidth
}

func (u *UpdateSettingsRequest) GetDefaultMaxHeight() optionalnullable.OptionalNullable[int64] {
	if u == nil {
		return nil
	}
	return u.DefaultMaxHeight
}

func (u *UpdateSettingsRequest) GetTheme() *string {
	if u == nil {
		return nil
	}
	return u.Theme
}

func (u *UpdateSettingsRequest) GetLanguage() *string {
	if u == nil {
		return nil
	}
	return u.Language
}
