// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateVisibilityResponse struct {
	// Image ID
	ID string `json:"id"`
	// Updated visibility
	Visibility Visibility `json:"visibility"`
	// Status message
	Message string `json:"message"`
}

func (u *UpdateVisibilityResponse) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateVisibilityResponse) GetVisibility() Visibility {
	if u == nil {
		return Visibility("")
	}
	return u.Visibility
}

func (u *UpdateVisibilityResponse) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}
