// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"github.com/img-src-io/sdk-go/optionalnullable"
)

type UpdatePresetRequest struct {
	// New preset name (1-50 characters)
	Name *string `json:"name,omitzero"`
	// New description (max 200 characters, null to clear)
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// New transformation parameters
	Params map[string]any `json:"params,omitzero"`
}

func (u UpdatePresetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdatePresetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdatePresetRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdatePresetRequest) GetDescription() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdatePresetRequest) GetParams() map[string]any {
	if u == nil {
		return nil
	}
	return u.Params
}
