// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/img-src-io/sdk-go/internal/utils"
	"time"
)

type UploadResponse struct {
	// Image ID (first 16 characters of SHA256 hash)
	ID string `json:"id"`
	// Full SHA256 hash of the image content
	Hash string `json:"hash"`
	// Primary CDN URL for the image
	URL string `json:"url"`
	// All paths where this image is accessible
	Paths []string `json:"paths"`
	// Whether this is a newly uploaded image (false if duplicate)
	IsNew *bool `json:"is_new,omitzero"`
	// File size in bytes
	Size int64 `json:"size"`
	// Detected image format
	Format           string           `json:"format"`
	Dimensions       *ImageDimensions `json:"dimensions,omitzero"`
	AvailableFormats AvailableFormats `json:"available_formats"`
	// Upload timestamp (RFC3339 format)
	UploadedAt time.Time    `json:"uploaded_at"`
	Links      HateoasLinks `json:"_links"`
}

func (u UploadResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadResponse) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UploadResponse) GetHash() string {
	if u == nil {
		return ""
	}
	return u.Hash
}

func (u *UploadResponse) GetURL() string {
	if u == nil {
		return ""
	}
	return u.URL
}

func (u *UploadResponse) GetPaths() []string {
	if u == nil {
		return []string{}
	}
	return u.Paths
}

func (u *UploadResponse) GetIsNew() *bool {
	if u == nil {
		return nil
	}
	return u.IsNew
}

func (u *UploadResponse) GetSize() int64 {
	if u == nil {
		return 0
	}
	return u.Size
}

func (u *UploadResponse) GetFormat() string {
	if u == nil {
		return ""
	}
	return u.Format
}

func (u *UploadResponse) GetDimensions() *ImageDimensions {
	if u == nil {
		return nil
	}
	return u.Dimensions
}

func (u *UploadResponse) GetAvailableFormats() AvailableFormats {
	if u == nil {
		return AvailableFormats{}
	}
	return u.AvailableFormats
}

func (u *UploadResponse) GetUploadedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UploadedAt
}

func (u *UploadResponse) GetLinks() HateoasLinks {
	if u == nil {
		return HateoasLinks{}
	}
	return u.Links
}
