// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PlanStatus - Current plan status
type PlanStatus string

const (
	PlanStatusActive     PlanStatus = "active"
	PlanStatusCancelling PlanStatus = "cancelling"
	PlanStatusExpired    PlanStatus = "expired"
)

func (e PlanStatus) ToPointer() *PlanStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlanStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "cancelling", "expired":
			return true
		}
	}
	return false
}

type UsageResponse struct {
	// User's plan ID
	Plan string `json:"plan"`
	// Human-readable plan name
	PlanName string `json:"plan_name"`
	// Current plan status
	PlanStatus PlanStatus `json:"plan_status"`
	// Unix timestamp when subscription ends (for cancelling plans)
	SubscriptionEndsAt *int64     `json:"subscription_ends_at"`
	PlanLimits         PlanLimits `json:"plan_limits"`
	// Total images (lifetime)
	TotalImages int64 `json:"total_images"`
	// Total storage used in bytes
	StorageUsedBytes int64 `json:"storage_used_bytes"`
	// Total storage used in MB
	StorageUsedMb float64 `json:"storage_used_mb"`
	// Total storage used in GB
	StorageUsedGb float64       `json:"storage_used_gb"`
	CurrentPeriod CurrentPeriod `json:"current_period"`
}

func (u *UsageResponse) GetPlan() string {
	if u == nil {
		return ""
	}
	return u.Plan
}

func (u *UsageResponse) GetPlanName() string {
	if u == nil {
		return ""
	}
	return u.PlanName
}

func (u *UsageResponse) GetPlanStatus() PlanStatus {
	if u == nil {
		return PlanStatus("")
	}
	return u.PlanStatus
}

func (u *UsageResponse) GetSubscriptionEndsAt() *int64 {
	if u == nil {
		return nil
	}
	return u.SubscriptionEndsAt
}

func (u *UsageResponse) GetPlanLimits() PlanLimits {
	if u == nil {
		return PlanLimits{}
	}
	return u.PlanLimits
}

func (u *UsageResponse) GetTotalImages() int64 {
	if u == nil {
		return 0
	}
	return u.TotalImages
}

func (u *UsageResponse) GetStorageUsedBytes() int64 {
	if u == nil {
		return 0
	}
	return u.StorageUsedBytes
}

func (u *UsageResponse) GetStorageUsedMb() float64 {
	if u == nil {
		return 0.0
	}
	return u.StorageUsedMb
}

func (u *UsageResponse) GetStorageUsedGb() float64 {
	if u == nil {
		return 0.0
	}
	return u.StorageUsedGb
}

func (u *UsageResponse) GetCurrentPeriod() CurrentPeriod {
	if u == nil {
		return CurrentPeriod{}
	}
	return u.CurrentPeriod
}
