// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserSettings struct {
	// Clerk user ID
	ID string `json:"id"`
	// Username
	Username string `json:"username"`
	// Email address
	Email *string `json:"email,omitzero"`
	// Preferred delivery formats (ordered)
	DeliveryFormats []string `json:"delivery_formats"`
	// Default image quality (1-100)
	DefaultQuality int64 `json:"default_quality"`
	// Default fit mode
	DefaultFitMode string `json:"default_fit_mode"`
	// Default maximum width
	DefaultMaxWidth *int64 `json:"default_max_width,omitzero"`
	// Default maximum height
	DefaultMaxHeight *int64 `json:"default_max_height,omitzero"`
	// UI theme
	Theme string `json:"theme"`
	// UI language
	Language string `json:"language"`
	// Account creation timestamp (Unix epoch)
	CreatedAt int64 `json:"created_at"`
	// Last update timestamp (Unix epoch)
	UpdatedAt int64 `json:"updated_at"`
	// Total number of uploads
	TotalUploads int64 `json:"total_uploads"`
	// Total storage used in bytes
	StorageUsedBytes int64 `json:"storage_used_bytes"`
}

func (u *UserSettings) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UserSettings) GetUsername() string {
	if u == nil {
		return ""
	}
	return u.Username
}

func (u *UserSettings) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserSettings) GetDeliveryFormats() []string {
	if u == nil {
		return []string{}
	}
	return u.DeliveryFormats
}

func (u *UserSettings) GetDefaultQuality() int64 {
	if u == nil {
		return 0
	}
	return u.DefaultQuality
}

func (u *UserSettings) GetDefaultFitMode() string {
	if u == nil {
		return ""
	}
	return u.DefaultFitMode
}

func (u *UserSettings) GetDefaultMaxWidth() *int64 {
	if u == nil {
		return nil
	}
	return u.DefaultMaxWidth
}

func (u *UserSettings) GetDefaultMaxHeight() *int64 {
	if u == nil {
		return nil
	}
	return u.DefaultMaxHeight
}

func (u *UserSettings) GetTheme() string {
	if u == nil {
		return ""
	}
	return u.Theme
}

func (u *UserSettings) GetLanguage() string {
	if u == nil {
		return ""
	}
	return u.Language
}

func (u *UserSettings) GetCreatedAt() int64 {
	if u == nil {
		return 0
	}
	return u.CreatedAt
}

func (u *UserSettings) GetUpdatedAt() int64 {
	if u == nil {
		return 0
	}
	return u.UpdatedAt
}

func (u *UserSettings) GetTotalUploads() int64 {
	if u == nil {
		return 0
	}
	return u.TotalUploads
}

func (u *UserSettings) GetStorageUsedBytes() int64 {
	if u == nil {
		return 0
	}
	return u.StorageUsedBytes
}
