// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Visibility - Image visibility setting
type Visibility string

const (
	VisibilityPublic  Visibility = "public"
	VisibilityPrivate Visibility = "private"
)

func (e Visibility) ToPointer() *Visibility {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Visibility) IsExact() bool {
	if e != nil {
		switch *e {
		case "public", "private":
			return true
		}
	}
	return false
}
